image: rustlang/rust:nightly

pipelines:
  default:
    - step:
        name: "Build and Test"
        caches:
          - cargo
          - rust-target
        script:
          - echo "Setup git with read/write access"   ; sh scripts/setup-git.sh
          - echo "Testing code"                       ; cargo test
          - echo "Building libs and applications"     ; cargo build --release
  branches:
    master:
      - step:
          name: "Release Artifacts"
          caches:
            - cargo
            - rust-target
          script:
            - echo "Setup git with read/write access"   ; sh scripts/setup-git.sh
            - echo "Testing code"                       ; cargo test
            - echo "Building libs and applications"     ; cargo build --release
            - pipe: atlassian/bitbucket-upload-file:0.3.4
              variables:
                BITBUCKET_USERNAME: SSTentacleSS
                BITBUCKET_APP_PASSWORD: $BITBUCKET_DEPLOY_PASSWORD
                FILENAME: "$BITBUCKET_CLONE_DIR/target/release/*.rlib"
            - pipe: atlassian/bitbucket-upload-file:0.3.4
              variables:
                BITBUCKET_USERNAME: SSTentacleSS
                BITBUCKET_APP_PASSWORD: $BITBUCKET_DEPLOY_PASSWORD
                FILENAME: "$BITBUCKET_CLONE_DIR/target/release/fastdustry-demo"
definitions:
  caches:
    cargo: /usr/local/cargo
    rust-target: $BITBUCKET_CLONE_DIR/target